@startuml
|Player|
start
:Opponent receive link join from others player;
:Opponent click link;
:Opponent join room;
|System|
:Notify room creator of new player;
|Player|
:Wait for game to start;
stop
@enduml
