@startuml
|Player|
start
:Player send request endgame;
|System|
if (Request resign?) then (yes)
:Win for opponent;
(no) elseif (Request a draw?) then (yes)
  :Draw;
else (no)
  :Continue game;
endif
stop
@enduml
