@startuml useCaseDiagram
left to right direction
actor Guest 
rectangle {
    usecase "sign up"as signUp
    usecase "login"as login
}
actor Player
rectangle "System Boundary" {
    usecase "Move Piece"as movePiece
    usecase "Chat" as chat
    usecase "Request Endgame" as requestEndgame
    usecase "Play Game" as playGame
    usecase "Invite" as invite
    usecase "Create Room" as createRoom
    usecase "Join Room" as joinRoom
    usecase "Create Room" as createGame
}
Guest --> signUp
Guest --> login

Player --> movePiece
Player --> chat
Player --> requestEndgame
Player --> playGame
Player --> invite
Player --> createRoom
Player --> joinRoom
Player --> createGame
@endum