@startuml classDiagram
class Board {
    cell
    resetBoard()
    getCell()
    setCell()
}
class Game {
    player
    board
    currentTurn
    endGame
    listMoved
    makeMove()
    switchTurn()
    isCheck()
    isCheckMate()
    isStealMate()
    isDraw()
    isEndGame()
}

class Cell {
    -piece: Piece
    -column: String 
    -row: int

    +Cell(piece: Piece, row: int, column: String)
    +getPiece(): Piece
    +setPiece(piece: Piece): void
    +isOccupied(): boolean
    +getRow(): int
    +getColumn() : String
}
abstract class PlayerBase {
    -name: String
    -whiteSide: Boolean
    -game: Game
    
    +PlayerBase(name: String, whiteSide: Boolean)
    +isWhiteSide(): Boolean
    +joinGame(game: Game): void
    +createRoom(): Game
    +startGame(): void
    +resign(): void
    +makeDraw(): void
    +sendMessage(message: String): void
}

abstract class PieceBase {
    -name: String
    -whitePiece: boolean

    +findValidMove(cell: Cell): void
    +isWhitePiece(): Boolean
}

class Move {
    -playerMakeMove : Player
    -startCell : Cell 
    -endCell : Cell

    +isValidMove(): Boolean
}

PlayerBase --> Game
Cell --> Board
Cell -->PieceBase
Board --> Game
Game --> GameStatus
Game --> Move

@enduml


