@startuml classDiagram
class Board {
    cell
    resetBoard()
    getCell()
    setCell()
}
class Game {
    player
    board
    currentTurn
    endGame
    listMoved
    makeMove()
    switchTurn()
    isCheck()
    isCheckMate()
    isStealMate()
    isDraw()
    isEndGame()
}
@enduml