@startuml
start
:Player selects a piece;
:Show Validate Move;
:Player selects a destination;
if (Valid move?) then (yes)
    :Move Piece;
    :Save History Move;
else (no)
    :Display Invalid Move Message;
endif
stop
@enduml
